// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALq4CovdqgaS3-yW3iX0aCw0BBGxv5es4',
    appId: '1:855940616320:web:5f958212fde87952225665',
    messagingSenderId: '855940616320',
    projectId: 'login-assessment-62998',
    authDomain: 'login-assessment-62998.firebaseapp.com',
    storageBucket: 'login-assessment-62998.appspot.com',
    measurementId: 'G-B54D55QX1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfLRSulvoTVero57dbGa5EkhMqWj1RGZA',
    appId: '1:855940616320:android:f766c3778d58813f225665',
    messagingSenderId: '855940616320',
    projectId: 'login-assessment-62998',
    storageBucket: 'login-assessment-62998.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqiyuncDsa65cf_jxaUDKK85CusHIR9Ps',
    appId: '1:855940616320:ios:7c25558c66e2d336225665',
    messagingSenderId: '855940616320',
    projectId: 'login-assessment-62998',
    storageBucket: 'login-assessment-62998.appspot.com',
    iosClientId: '855940616320-mr28th8ub05bsca72gu0b9lhhlnpsil8.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqiyuncDsa65cf_jxaUDKK85CusHIR9Ps',
    appId: '1:855940616320:ios:7c25558c66e2d336225665',
    messagingSenderId: '855940616320',
    projectId: 'login-assessment-62998',
    storageBucket: 'login-assessment-62998.appspot.com',
    iosClientId: '855940616320-mr28th8ub05bsca72gu0b9lhhlnpsil8.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAssessment',
  );
}
